import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from 'next/link';
import SidebarNav from "@/components/SidebarNav";

import {
  HiOutlineHome,
  HiOutlineUserGroup,
  HiOutlineChartBar,
  HiOutlineStar,
  HiOutlineShoppingBag,
  HiOutlineUserCircle,
  HiOutlineChatBubbleOvalLeft,
} from 'react-icons/hi2';
import { BsShop } from "react-icons/bs";
import { HiOutlineSearch } from "react-icons/hi";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kalgasov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-[#f9f9f9] ${geistMono.variable} antialiased`}
      >
        {/* Navbar */}
       <div className='bg-white fixed top-0 left-0 w-full flex py-4 border-b border-gray-200 z-10'>
        <div className="grid grid-cols-12 items-center flex px-10 w-[1200px] mx-auto">
           <a href='/' className='col-span-3 block'>
               <img
                src='/logo.png'
                className='w-[150px]'
                />
           </a> 
           <div className='col-span-7'>
            <div className="w-[300px] relative rounded-md shadow-sm">
                <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                  <span className="text-gray-500"><HiOutlineSearch /></span>
                </div>
                <input
                  id="price"
                  name="price"
                  type="text"
                  placeholder="Поиск по сайту"
                  className="block w-full rounded-md border-0 py-1.5 pl-10 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6"
                />
              </div>
           </div>
           <div className='col-span-2'>
                <a href='/user/aidosgal' className='flex items-center gap-x-3'>
                    <img
                        src='/default.png'
                        className='w-[40px] h-[40px] rounded-full object-contain'
                    />
                    <div>
                        <div>Айдос Галимжан</div>
                        <div className='text-gray-500 text-sm'>@aidosgal</div>
                    </div>
                </a>
           </div>
        </div>
       </div>

       <div className="grid grid-cols-12 mt-[90px] w-[1200px] mx-auto">
        
        <div className="col-span-3 sticky top-[80px] space-y-2 px-5 h-[calc(100vh-80px)] overflow-y-auto scrollbar-hide">
            <SidebarNav /> 
        </div>

        <div className="col-span-9 overflow-y-auto max-h-[calc(100vh-80px)] scrollbar-hide">
          {children}
        </div>
      </div> 
      </body>
    </html>
  );
}

