import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import {
  HiOutlineHome,
  HiOutlineUserGroup,
  HiOutlineChartBar,
  HiOutlineStar,
  HiOutlineShoppingBag,
  HiOutlineUserCircle,
  HiOutlineChatBubbleOvalLeft,
} from 'react-icons/hi2';
import { BsShop } from "react-icons/bs";
import { HiOutlineSearch } from "react-icons/hi";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Kalgasov",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} bg-[#f9f9f9] ${geistMono.variable} antialiased`}
      >
       <div className='bg-white flex py-4 border-b border-gray-200'>
        <div className="grid grid-cols-12 items-center flex px-10 w-[1200px] mx-auto">
           <div className='col-span-3'>
               <img
                src='/logo.png'
                className='w-[150px]'
                />
           </div> 
           <div className='col-span-7'>
            <div className="w-[300px] relative rounded-md shadow-sm">
                <div className="pointer-events-none absolute inset-y-0 left-0 flex items-center pl-3">
                  <span className="text-gray-500"><HiOutlineSearch /></span>
                </div>
                <input
                  id="price"
                  name="price"
                  type="text"
                  placeholder="Поиск по сайту"
                  className="block w-full rounded-md border-0 py-1.5 pl-10 text-gray-900 ring-1 ring-inset ring-gray-300 placeholder:text-gray-400 focus:ring-2 focus:ring-inset focus:ring-indigo-600 sm:text-sm/6"
                />
              </div>
           </div>
           <div className='col-span-2'>
                <div className='flex items-center gap-x-3'>
                    <img
                        src='/default.png'
                        className='w-[40px] h-[40px] rounded-full object-contain'
                    />
                    <div>
                        <div>Айдос Галимжан</div>
                        <div className='text-gray-500 text-sm'>@aidosgal</div>
                    </div>
                </div>
           </div>
        </div>
       </div>
       <div className="grid grid-cols-12 mt-5 w-[1200px] mx-auto">
        <div className="col-span-3 space-y-2 px-5">
          <div className="flex items-center gap-x-3  text-black w-full bg-white rounded-lg px-4 py-2 hover:text-black cursor-pointer">
            <HiOutlineHome className="text-2xl" />
            Лента
          </div>
          <div className="flex items-center gap-x-3 text-gray-600 hover:text-black cursor-pointer px-4 py-2">
            <HiOutlineUserGroup className="text-2xl" />
            Подписки
          </div>
          <div className="flex items-center gap-x-3 text-gray-600 hover:text-black cursor-pointer px-4 py-2">
            <HiOutlineChatBubbleOvalLeft className="text-2xl"/>
            Сообщения
          </div>
          <div className="flex items-center gap-x-3 text-gray-600 hover:text-black cursor-pointer px-4 py-2">
            <BsShop className="text-2xl"/>
            Магазины
          </div>
          <div className="flex items-center gap-x-3 text-gray-600 hover:text-black cursor-pointer px-4 py-2">
            <HiOutlineShoppingBag className="text-2xl"/>
            Товары
          </div>
          <div className="flex items-center gap-x-3 text-gray-600 hover:text-black cursor-pointer px-4 py-2">
            <HiOutlineStar className="text-2xl" />
            Избранные
          </div>
        </div>

        <div className="col-span-9">{children}</div>
      </div> 
      </body>
    </html>
  );
}
